### ISSUE TITLE
Unresolved reference: com during compile (debug apk)

### ISSUE THREAD

**Issue by deathblade666** [material-foundation/flutter-packages#610]
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

### What happened?
See logs below
## Expected vs actual result:
to resolve all imports

## Steps to reproduce:
1.
1.
1.

### Relevant log output
Flutter Doctor -v
```shell
[✓] Flutter (Channel stable, 3.24.1, on Arch Linux 6.10.4-arch2-1, locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (9 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/deathmasia/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 6.10.4-arch2-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

Build Error
```
e: ~/.pub-cache/hosted/pub.dev/dynamic_color-1.7.0/android/src/main/kotlin/io/material/plugins/dynamic_color/DynamicColorPlugin.kt: (11, 8): Unresolved reference: com
e: ~/.pub-cache/hosted/pub.dev/dynamic_color-1.7.0/android/src/main/kotlin/io/material/plugins/dynamic_color/DynamicColorPlugin.kt: (32, 13): Unresolved reference: DynamicColors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dynamic_color:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

It appears to be in issue directly with version 1.7.0 as it compiles fine with 1.6.9
